# Uncomment the next line to define a global platform for your project

target '17-Multistream' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 17-Multistream
  pod 'AGEVideoLayout'
  pod 'AgoraRtcEngine_macOS', '~> 3.0.1'
end
